# ML supervisé sur des données de vins

On récupère les données

In [1]:
import pandas as pd
import numpy as np

In [2]:
vin_blanc = pd.read_csv("./data/winequality-white.csv",sep=";")
vin_rouge = pd.read_csv("./data/winequality-red.csv",sep=";")

On crée une colonne associée à la couleur et on concatène les deux jeux de données

In [3]:
vin_blanc["couleur"] = "blanc"
vin_rouge["couleur"] = "rouge"

In [4]:
data = pd.concat([vin_rouge,vin_blanc],axis=0)

In [5]:
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality couleur  
0      9.4        5   rouge  
1      9.8        5   rouge  
2      9.8        5   rouge  
3      9.8        6   rouge  
4      9.4        5   rouge

In [6]:
print(vin_blanc.shape, vin_rouge.shape,data.shape)

(4898, 13) (1599, 13) (6497, 13)


## Séparation apprentissage / test

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x = data.drop(columns="couleur")
y = data["couleur"]

In [9]:
print(x.shape, y.shape)

(6497, 12) (6497,)


In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [11]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(4547, 12) (1950, 12) (4547,) (1950,)


## Ajustement des modèles

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier

In [13]:
# on crée un objet par modèle
model_logit = LogisticRegression()
model_rf = RandomForestClassifier()
model_gbm = GradientBoostingClassifier()
model_nn = MLPClassifier()
model_knn = KNeighborsClassifier()

In [14]:
# ajuster les paramètres des modèles
model_logit.fit(x_train,y_train)
model_rf.fit(x_train,y_train)
model_gbm.fit(x_train,y_train)
model_nn.fit(x_train,y_train)
model_knn.fit(x_train,y_train)

C:\Users\s4d-asus-14\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\s4d-asus-14\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [15]:
# on affiche les paramètres du modèle
print("constante :", model_logit.intercept_)
pd.DataFrame(model_logit.coef_,index=["coef"],columns=x_train.columns).T

constante : [-2.92579507]


coef
fixed acidity         0.688889
volatile acidity      7.828847
citric acid          -0.990035
residual sugar       -0.144104
chlorides             2.128232
free sulfur dioxide   0.047031
total sulfur dioxide -0.062646
density              -2.692594
pH                    2.221404
sulphates             6.190781
alcohol              -0.772776
quality              -0.123659

In [16]:
y_pred_logit = model_logit.predict(x_test)
y_pred_rf = model_rf.predict(x_test)
y_pred_gbm = model_gbm.predict(x_test)
y_pred_nn = model_nn.predict(x_test)
y_pred_knn = model_knn.predict(x_test)

## Indicateur de qualité du modèle

In [17]:
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score

In [18]:
print(accuracy_score(y_test,y_pred_logit))
print(accuracy_score(y_test,y_pred_rf))
print(accuracy_score(y_test,y_pred_gbm))
print(accuracy_score(y_test,y_pred_nn))
print(accuracy_score(y_test,y_pred_knn))


0.981025641025641
0.9948717948717949
0.9958974358974358
0.9815384615384616
0.9343589743589743


In [19]:
print(confusion_matrix(y_test,y_pred_logit))
print(confusion_matrix(y_test,y_pred_rf))
print(confusion_matrix(y_test,y_pred_gbm))
print(confusion_matrix(y_test,y_pred_nn))
print(confusion_matrix(y_test,y_pred_knn))

[[1481   19]
 [  18  432]]
[[1497    3]
 [   7  443]]
[[1497    3]
 [   5  445]]
[[1483   17]
 [  19  431]]
[[1448   52]
 [  76  374]]
